language: node_js
node_js:
  - lts/*
install:
  - pnpm install # npm ci
script:
  - pnpm run Rarrot:build # npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: Rarrot/.vitepress/dist
  # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
  github_token: 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
  keep_history: true
  on:
    branch: main